2018-12-08 18:03:32 Thread-5 ERROR [demo.App.logError(App.java:56)] An unexpected error occurred in Thread[Thread-5,5,main]
java.lang.IllegalArgumentException: size of array must be MAX_ID_COUNT size
	at org.jnetpcap.packet.JScanner.loadScanners(Native Method)
	at org.jnetpcap.packet.JScanner.reloadAll(Unknown Source)
	at org.jnetpcap.packet.JScanner.<init>(Unknown Source)
	at org.jnetpcap.packet.JScanner.<init>(Unknown Source)
	at org.jnetpcap.packet.JPacket.getDefaultScanner(Unknown Source)
	at org.jnetpcap.packet.JScanner.getThreadLocal(Unknown Source)
	at org.jnetpcap.Pcap.loop(Unknown Source)
	at packet.PackageCapture.mainCapture(PackageCapture.java:200)
	at demo.controller.HomeController$1$1.run(HomeController.java:84)
	at java.lang.Thread.run(Unknown Source)
